#!/usr/bin/env python3
"""Apply in-context (human/Claude-judged) classifications to the sample and
write data/reviews_classified.json in the SAME schema analyze.py produces.

Each sid maps to: [funnel_stage, theme, jtbd, sentiment, competitor(0/1), feature]
Judgments authored by reading data/sample.txt (see teardown methodology note).
"""
import json
from pathlib import Path

DATA = Path(__file__).parent / "data"
sample = {r["sid"]: r for r in json.load(open(DATA / "sample.json"))}

# fmt: off
C = {
0:["activation","reliability","unknown","negative",0,""],
1:["retention","reliability","unknown","negative",0,""],
2:["activation","reliability","unknown","negative",0,""],
3:["activation","app_booking_ux","unknown","negative",0,"flag commercial vs residential at booking"],
4:["acquisition","supply_availability","unknown","negative",0,""],
5:["activation","reliability","unknown","negative",0,""],
6:["activation","reliability","unknown","negative",0,""],
7:["activation","reliability","unknown","negative",0,""],
8:["revenue","pricing_value","unknown","negative",0,""],
9:["retention","reliability","unknown","negative",0,""],
10:["retention","reliability","unknown","negative",0,""],
11:["revenue","support_refunds","unknown","negative",0,""],
12:["activation","support_refunds","unknown","negative",0,""],
13:["retention","pro_quality","unknown","negative",0,""],
14:["activation","reliability","unknown","negative",0,""],
15:["activation","support_refunds","unknown","negative",0,""],
16:["retention","reliability","unknown","negative",0,""],
17:["activation","reliability","unknown","negative",0,""],
18:["activation","reliability","unknown","negative",0,""],
19:["activation","reliability","unknown","negative",0,""],
20:["retention","reliability","unknown","negative",0,""],
21:["activation","app_booking_ux","unknown","negative",0,"payment-confirmation mismatch"],
22:["activation","reliability","unknown","negative",0,""],
23:["activation","reliability","unknown","negative",0,"cancel button not working"],
24:["activation","reliability","unknown","negative",0,""],
25:["acquisition","supply_availability","unknown","negative",0,"expand service area"],
26:["retention","reliability","unknown","negative",0,""],
27:["retention","pro_quality","unknown","negative",0,""],
28:["activation","reliability","unknown","negative",0,""],
29:["activation","reliability","unknown","negative",0,""],
30:["retention","reliability","unknown","negative",0,""],
31:["retention","reliability","unknown","negative",0,""],
32:["retention","pro_quality","unknown","negative",0,""],
33:["retention","reliability","unknown","negative",0,""],
34:["retention","reliability","unknown","negative",0,""],
35:["activation","reliability","unknown","negative",0,""],
36:["retention","app_booking_ux","routine","negative",0,"reuse saved addresses"],
37:["retention","reliability","unknown","negative",0,""],
38:["activation","reliability","unknown","negative",0,""],
39:["activation","reliability","unknown","negative",0,"allow cancel when pro is late"],
40:["retention","reliability","unknown","negative",0,""],
41:["activation","reliability","unknown","negative",0,""],
42:["retention","support_refunds","unknown","negative",0,""],
43:["activation","reliability","maid_gap","negative",0,""],
44:["activation","reliability","unknown","negative",0,""],
45:["activation","pro_quality","unknown","negative",1,""],
46:["retention","reliability","unknown","negative",1,""],
47:["retention","reliability","unknown","negative",0,""],
48:["retention","reliability","unknown","negative",0,""],
49:["activation","reliability","unknown","negative",0,""],
50:["retention","reliability","unknown","negative",0,""],
51:["activation","reliability","unknown","negative",0,""],
52:["activation","reliability","unknown","negative",0,""],
53:["activation","app_booking_ux","unknown","negative",0,"chat screen flickers"],
54:["acquisition","supply_availability","unknown","negative",0,"don't allow address in unserviced area"],
55:["retention","pro_quality","unknown","negative",0,""],
56:["acquisition","supply_availability","unknown","negative",0,""],
57:["acquisition","supply_availability","unknown","negative",0,"expand area Indore"],
58:["activation","support_refunds","unknown","negative",0,""],
59:["activation","reliability","unknown","negative",0,""],
60:["retention","reliability","unknown","negative",0,""],
61:["activation","support_refunds","unknown","mixed",0,""],
62:["retention","reliability","unknown","negative",0,""],
63:["retention","reliability","routine","negative",0,""],
64:["revenue","pricing_value","unknown","negative",0,"clarify refund amount at cancel"],
65:["activation","reliability","unknown","negative",0,""],
66:["activation","supply_availability","unknown","negative",0,""],
67:["activation","reliability","unknown","negative",0,""],
68:["revenue","support_refunds","unknown","negative",0,""],
69:["acquisition","reliability","unknown","negative",0,""],
70:["retention","pro_quality","unknown","negative",0,""],
71:["activation","reliability","unknown","negative",0,""],
72:["activation","reliability","unknown","negative",0,""],
73:["retention","reliability","unknown","negative",0,""],
74:["retention","pro_quality","unknown","negative",0,""],
75:["activation","reliability","unknown","negative",0,""],
76:["activation","app_booking_ux","unknown","negative",0,""],
77:["activation","reliability","unknown","negative",0,""],
78:["retention","reliability","unknown","negative",0,""],
79:["acquisition","supply_availability","unknown","negative",0,"expand Bangalore 560084"],
80:["activation","reliability","unknown","negative",0,""],
81:["retention","reliability","unknown","negative",0,""],
82:["activation","reliability","unknown","negative",1,""],
83:["retention","reliability","unknown","negative",0,""],
84:["revenue","pricing_value","unknown","negative",0,""],
85:["activation","reliability","unknown","negative",0,"hire more staff"],
86:["activation","reliability","unknown","negative",0,""],
87:["activation","reliability","unknown","negative",0,""],
88:["retention","reliability","unknown","negative",0,""],
89:["retention","reliability","unknown","negative",0,""],
90:["activation","reliability","unknown","negative",0,""],
91:["activation","pro_quality","unknown","negative",0,""],
92:["retention","support_refunds","unknown","negative",0,""],
93:["activation","reliability","unknown","negative",0,""],
94:["activation","reliability","unknown","negative",0,""],
95:["activation","pro_quality","unknown","negative",0,""],
96:["activation","reliability","unknown","negative",0,""],
97:["acquisition","supply_availability","unknown","negative",0,""],
98:["retention","reliability","unknown","negative",0,""],
99:["retention","reliability","unknown","negative",0,""],
100:["retention","reliability","unknown","negative",0,""],
101:["acquisition","supply_availability","unknown","negative",0,""],
102:["retention","support_refunds","unknown","negative",0,""],
103:["retention","reliability","unknown","negative",0,""],
104:["activation","reliability","unknown","negative",0,""],
105:["retention","pro_quality","unknown","negative",0,""],
106:["activation","reliability","unknown","negative",0,""],
107:["revenue","support_refunds","unknown","negative",0,""],
108:["activation","reliability","unknown","negative",0,""],
109:["activation","pro_quality","unknown","negative",0,""],
110:["activation","reliability","unknown","negative",0,""],
111:["activation","reliability","unknown","negative",0,""],
112:["activation","reliability","unknown","negative",0,""],
113:["activation","support_refunds","unknown","negative",0,""],
114:["activation","reliability","unknown","negative",0,""],
115:["activation","reliability","unknown","negative",0,""],
116:["retention","support_refunds","unknown","negative",0,""],
117:["activation","reliability","unknown","negative",0,""],
118:["activation","supply_availability","life_change","negative",0,""],
119:["retention","reliability","unknown","negative",0,""],
120:["activation","app_booking_ux","unknown","negative",0,"support screen blinks"],
121:["retention","reliability","routine","negative",0,""],
122:["retention","reliability","routine","mixed",0,"fix allocation for advance bookings"],
123:["activation","reliability","unknown","negative",0,""],
124:["activation","support_refunds","unknown","negative",0,""],
125:["revenue","pro_quality","unknown","negative",0,""],
126:["activation","reliability","unknown","negative",1,""],
127:["activation","reliability","unknown","negative",0,""],
128:["retention","reliability","unknown","negative",0,""],
129:["activation","reliability","unknown","negative",0,""],
130:["retention","reliability","unknown","negative",0,""],
131:["activation","reliability","unknown","negative",0,""],
132:["retention","support_refunds","unknown","negative",0,""],
133:["retention","reliability","unknown","negative",0,""],
134:["activation","reliability","unknown","negative",0,""],
135:["retention","pro_quality","unknown","negative",0,""],
136:["activation","reliability","unknown","negative",0,""],
137:["activation","reliability","unknown","negative",0,""],
138:["activation","reliability","unknown","negative",0,""],
139:["activation","pro_quality","unknown","negative",0,""],
140:["activation","pro_quality","unknown","negative",0,""],
141:["activation","reliability","unknown","negative",0,"don't charge double on reschedule"],
142:["acquisition","supply_availability","unknown","negative",0,""],
143:["retention","reliability","routine","negative",0,""],
144:["activation","reliability","unknown","negative",0,""],
145:["activation","support_refunds","unknown","negative",0,""],
146:["activation","reliability","unknown","negative",1,""],
147:["retention","reliability","unknown","negative",0,""],
148:["activation","reliability","unknown","negative",0,""],
149:["retention","reliability","unknown","negative",0,""],
150:["activation","reliability","life_change","positive",0,""],
151:["retention","pro_quality","unknown","positive",0,""],
152:["none","other","unknown","positive",0,""],
153:["none","other","unknown","positive",0,""],
154:["revenue","pricing_value","unknown","positive",0,""],
155:["none","other","unknown","positive",0,""],
156:["acquisition","app_booking_ux","unknown","positive",0,""],
157:["none","other","unknown","positive",0,""],
158:["none","other","unknown","positive",0,""],
159:["none","other","unknown","positive",0,""],
160:["none","other","unknown","positive",0,""],
161:["retention","pro_quality","unknown","positive",0,""],
162:["none","app_booking_ux","unknown","positive",0,""],
163:["activation","reliability","unknown","positive",0,""],
164:["acquisition","other","unknown","positive",0,""],
165:["none","other","unknown","positive",0,""],
166:["none","other","unknown","positive",0,""],
167:["none","other","unknown","positive",0,""],
168:["referral","other","unknown","positive",0,""],
169:["referral","other","unknown","positive",0,""],
170:["activation","reliability","unknown","positive",0,""],
171:["none","other","unknown","positive",0,""],
172:["none","other","unknown","positive",0,""],
173:["none","other","unknown","positive",0,""],
174:["none","other","unknown","positive",0,""],
175:["none","other","unknown","positive",0,""],
176:["none","other","unknown","positive",0,""],
177:["retention","pro_quality","unknown","positive",0,""],
178:["none","other","unknown","positive",0,""],
179:["activation","app_booking_ux","unknown","positive",0,""],
180:["activation","reliability","life_change","positive",0,""],
181:["retention","pro_quality","unknown","positive",0,""],
182:["none","app_booking_ux","unknown","positive",0,""],
183:["revenue","pricing_value","unknown","positive",0,""],
184:["none","other","unknown","positive",0,""],
185:["activation","pro_quality","unknown","positive",0,""],
186:["activation","app_booking_ux","unknown","positive",0,""],
187:["revenue","pricing_value","unknown","positive",0,""],
188:["none","other","unknown","positive",0,""],
189:["none","other","unknown","positive",0,""],
190:["none","other","unknown","positive",0,""],
191:["none","other","unknown","positive",0,""],
192:["activation","reliability","unknown","positive",0,""],
193:["retention","pro_quality","unknown","positive",0,""],
194:["activation","reliability","event_guests","positive",0,""],
195:["none","other","unknown","positive",0,""],
196:["retention","pro_quality","routine","positive",0,""],
197:["none","other","unknown","positive",0,""],
198:["none","other","unknown","positive",0,""],
199:["retention","pro_quality","unknown","positive",0,""],
200:["none","other","unknown","positive",0,""],
201:["activation","other","routine","positive",0,""],
202:["activation","reliability","maid_gap","positive",0,""],
203:["none","other","unknown","positive",0,""],
204:["activation","pricing_value","unknown","positive",0,""],
205:["activation","reliability","unknown","negative",0,""],
206:["retention","support_refunds","unknown","negative",0,""],
207:["activation","app_booking_ux","unknown","positive",0,""],
208:["activation","app_booking_ux","unknown","mixed",0,"fix payment-flow crashes and logout"],
209:["none","other","unknown","positive",0,""],
210:["referral","other","unknown","positive",0,""],
211:["retention","other","routine","mixed",0,"add cooking service (chapatis)"],
212:["activation","pro_quality","unknown","positive",0,""],
213:["activation","scheduling","unknown","mixed",0,"pros arriving early"],
214:["activation","reliability","unknown","negative",0,"'2 minutes away' ETA is fake"],
215:["activation","support_refunds","unknown","negative",0,"chat option missing when CC redirects to it"],
216:["retention","pro_quality","unknown","positive",0,""],
217:["retention","pro_quality","unknown","mixed",0,"add way to rate/report a pro"],
218:["retention","reliability","unknown","mixed",0,""],
219:["retention","pro_quality","unknown","positive",0,""],
220:["revenue","support_refunds","unknown","negative",0,""],
221:["retention","pro_quality","unknown","negative",0,""],
222:["retention","pro_quality","unknown","negative",0,""],
223:["revenue","pricing_value","unknown","negative",0,""],
224:["retention","reliability","unknown","negative",0,""],
225:["retention","pro_quality","unknown","negative",0,""],
226:["retention","pro_quality","unknown","negative",0,""],
227:["retention","pro_quality","unknown","negative",0,""],
228:["revenue","pricing_value","unknown","negative",0,""],
229:["activation","pro_quality","unknown","negative",0,""],
230:["retention","pro_quality","unknown","negative",0,""],
231:["retention","other","unknown","negative",0,""],
232:["retention","pro_quality","unknown","negative",0,""],
233:["none","other","unknown","negative",0,""],
234:["retention","pro_quality","unknown","negative",0,""],
235:["activation","reliability","unknown","negative",0,""],
236:["revenue","pricing_value","unknown","negative",0,""],
237:["revenue","pricing_value","unknown","negative",0,""],
238:["retention","pro_quality","unknown","negative",0,""],
239:["retention","support_refunds","unknown","negative",0,""],
240:["retention","pro_quality","unknown","negative",0,""],
241:["revenue","pricing_value","unknown","negative",0,""],
242:["revenue","support_refunds","unknown","negative",0,""],
243:["retention","pro_quality","unknown","negative",0,""],
244:["retention","support_refunds","unknown","negative",0,""],
245:["activation","app_booking_ux","unknown","negative",0,""],
246:["retention","reliability","unknown","negative",0,""],
247:["acquisition","app_booking_ux","unknown","negative",0,"add screen-reader accessibility"],
248:["retention","pro_quality","unknown","negative",0,""],
249:["revenue","pricing_value","unknown","negative",0,""],
250:["retention","pro_quality","unknown","negative",0,""],
251:["revenue","pricing_value","unknown","negative",0,""],
252:["retention","pro_quality","unknown","negative",0,""],
253:["retention","support_refunds","unknown","negative",0,""],
254:["revenue","pricing_value","unknown","negative",0,""],
255:["revenue","support_refunds","unknown","negative",0,""],
256:["revenue","support_refunds","unknown","negative",0,""],
257:["retention","pro_quality","unknown","negative",0,""],
258:["retention","support_refunds","unknown","negative",0,""],
259:["retention","pro_quality","unknown","negative",0,""],
260:["activation","reliability","event_guests","negative",0,""],
261:["revenue","pricing_value","unknown","negative",0,""],
262:["acquisition","supply_availability","unknown","negative",0,""],
263:["retention","reliability","unknown","negative",0,""],
264:["revenue","pricing_value","unknown","negative",0,""],
}
# fmt: on

KEYS = ["funnel_stage", "theme", "jtbd", "sentiment", "competitor_mention", "feature_request"]
out = []
for sid, vals in C.items():
    rec = dict(sample[sid])
    cls = dict(zip(KEYS, vals))
    cls["competitor_mention"] = bool(cls["competitor_mention"])
    out.append({**rec, **cls})

json.dump(out, open(DATA / "reviews_classified.json", "w"), ensure_ascii=False, indent=2)
print(f"Wrote {len(out)} classified reviews -> data/reviews_classified.json")
assert len(C) == 265, f"expected 265, got {len(C)}"
